/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_hank_learnjni_LearnJni */

#ifndef _Included_com_hank_learnjni_LearnJni
#define _Included_com_hank_learnjni_LearnJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hank_learnjni_LearnJni_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    getStringFromC1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hank_learnjni_LearnJni_getStringFromC1
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_changeName
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessArrayField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessArrayField
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessConstructorMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessConstructorMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessNonvirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessNonvirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    chineseChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hank_learnjni_LearnJni_chineseChars
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
