/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_hank_learnjni_LearnJni */

#ifndef _Included_com_hank_learnjni_LearnJni
#define _Included_com_hank_learnjni_LearnJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hank_learnjni_LearnJni_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    getStringFromC1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hank_learnjni_LearnJni_getStringFromC1
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_changeName
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessArrayField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessArrayField
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessConstructorMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessConstructorMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    accessNonvirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_accessNonvirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    chineseChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hank_learnjni_LearnJni_chineseChars
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    giveArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_giveArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    getArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hank_learnjni_LearnJni_getArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    localDef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_localDef
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    createGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_createGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    getGlobalRef
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_hank_learnjni_LearnJni_getGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_hank_learnjni_LearnJni
 * Method:    deleteGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hank_learnjni_LearnJni_deleteGlobalRef
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
